#!/usr/bin/sh

killall -q sxhkd
killall -q picom
killall -q polybar
killall -q nm-applet

sxhkd &
picom &
polybar	example &
nm-applet &
#feh --bg-center /usr/share/wallpapers/Next/contents/images/1920x1080.jpg
feh --bg-scale ~/Pictures/kanagawa.jpg
/usr/libexec/kf5/polkit-kde-authentication-agent-1

bspc monitor -d I II III IV V

bspc config border_width        2
bspc config window_gap          10
bspc config left_padding        5 
bspc config right_padding       5

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        false
bspc config single_monocle         false
bspc config focus_follows_pointer  true

bspc config normal_border_color \#090618
bspc config focused_border_color \#c34043
bspc config active_border_color \#c0a36e


